name: Release

on:
  workflow_dispatch:
    inputs:
      version_suffix:
        description: 'The version suffix for this manual build.'
        required: false
  push:
    tags:
      - "v*"

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    name: Unix Release (Ubuntu Host)
    env:
      VERSION_SUFFIX: ${{ github.event.inputs.version_suffix }}
    steps:
      - name: Install required packages
        run: sudo apt install -y debhelper dotnet-sdk-8.0

      - name: Checkout OpenTabletDriver Repository
        uses: actions/checkout@v4

      - name: Debian Build
        run: ./eng/linux/package.sh --package Debian --output ./dist/debian

      - name: Generic Linux Build
        run: ./eng/linux/package.sh --package BinaryTarBall --output ./dist/tarball

      - name: MacOS Build
        run: ./eng/macos/package.sh --package true --output ./dist/macos

      - name: Upload all artifacts (Release)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: OpenTabletDriver v${{ github.ref_name }}
          draft: true
          files: |
            ./dist/debian/*.deb
            ./dist/tarball/*.tar.gz
            ./dist/macos/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Debian artifact (Dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v3.1.3
        with:
          name: OpenTabletDriver.deb
          path: ./dist/debian/*.deb

      - name: Upload generic Linux artifact (Dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v3.1.3
        with:
          name: OpenTabletDriver.linux-x64.tar.gz
          path: ./dist/tarball/*.tar.gz

      - name: Upload macOS artifact (Dispatch)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v3.1.3
        with:
          name: OpenTabletDriver.osx-arm64.tar.gz
          path: ./dist/macos/*.tar.gz
